## 01. NumPy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨


### 1-1. nbarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [20]:
import numpy as np

In [21]:
# nbarry의 생성
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조 : {a.shape}")
print(f"배열의 구조 : {b.shape}")

# 배열의 차원 수
print(f"배열의 차원 수 : {a.ndim}")
print(f"배열의 차원 수 : {b.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입 : {a.dtype}")
print(f"배열의 데이터 타입 : {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입 : {new_a.dtype}")

배열의 구조 : (2, 3)
배열의 구조 : (3,)
배열의 차원 수 : 2
배열의 차원 수 : 1
배열의 데이터 타입 : int64
배열의 데이터 타입 : float64
수정한 배열의 데이터 타입 : float64


In [22]:
# 3차원 행렬
a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (3, 2, 3)
배열의 차원 수 : 3


In [23]:
# 4차원 행렬
a = np.array([[[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]],
              [[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (2, 3, 2, 3)
배열의 차원 수 : 4


### 1-2. 배열 초기화

In [26]:
# 모든 요소가 0인 배열 생성
np.zeros((3, 4)) # 2차원
np.zeros((2, 3, 4), dtype=np.int64) # 3차원


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [28]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [33]:
# 주어진 값으로 채운 배열
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [42]:
# 단위 행렬
np.eye(3, 3)
np.eye(3, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### 1-3. 범위 기반 배열 생성

In [45]:
# arange : range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [47]:
# linspace : 시작부터 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 1-4. 랜덤 배열 생성

In [49]:
# random.rand(m, n) : 0 ~ 1 사이의 난수로 초기화
np.random.rand(2, 3)

array([[0.6421659 , 0.1308671 , 0.54735134],
       [0.98178977, 0.19483147, 0.64470798]])

In [51]:
# random.randn(m, n) : 표준 정규분포를 따르는 난수로 초기화
# 표준 정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

array([[[ 0.72299939,  1.45807969,  0.81385393,  1.80667294,
          0.08851201],
        [-0.56142433,  0.29327721,  0.00509149, -0.01132654,
         -1.05498569],
        [ 0.77023015,  0.8054955 ,  0.37505136,  1.94578516,
          1.62584554],
        [-0.50188256,  0.20536421, -1.30554645, -0.20693052,
         -0.25575946]],

       [[ 0.62895701, -0.73185045,  0.91954336, -0.59873317,
         -0.59707902],
        [ 1.67709522, -1.40325164, -0.85073583, -0.65153834,
          0.95015794],
        [ 1.06028983, -0.76885008,  1.78026942,  0.62166423,
         -1.85155597],
        [ 1.06700291,  1.48415771, -0.21293611, -0.28663062,
          1.27736303]]])

In [52]:
# random.randint(low, high, (size)) : low이상 high미만의 숫자로 size 형태의 정수 배열을 생성
np.random.randint(10, 20, (2, 4))

array([[13, 16, 18, 13],
       [17, 10, 13, 17]], dtype=int32)