## 01. NumPy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨


### 1-1. nbarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [3]:
import numpy as np

In [4]:
# nbarry의 생성
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조 : {a.shape}")
print(f"배열의 구조 : {b.shape}")

# 배열의 차원 수
print(f"배열의 차원 수 : {a.ndim}")
print(f"배열의 차원 수 : {b.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입 : {a.dtype}")
print(f"배열의 데이터 타입 : {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입 : {new_a.dtype}")

배열의 구조 : (2, 3)
배열의 구조 : (3,)
배열의 차원 수 : 2
배열의 차원 수 : 1
배열의 데이터 타입 : int64
배열의 데이터 타입 : float64
수정한 배열의 데이터 타입 : float64


In [5]:
# 3차원 행렬
a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (3, 2, 3)
배열의 차원 수 : 3


In [6]:
# 4차원 행렬
a = np.array([[[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]],
              [[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (2, 3, 2, 3)
배열의 차원 수 : 4


### 1-2. 배열 초기화

In [7]:
# 모든 요소가 0인 배열 생성
np.zeros((3, 4)) # 2차원
np.zeros((2, 3, 4), dtype=np.int64) # 3차원


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [8]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [10]:
# 주어진 값으로 채운 배열
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [11]:
# 단위 행렬
np.eye(3, 3)
np.eye(3, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### 1-3. 범위 기반 배열 생성

In [12]:
# arange : range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
# linspace : 시작부터 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 1-4. 랜덤 배열 생성

In [14]:
# random.rand(m, n) : 0 ~ 1 사이의 난수로 초기화
np.random.rand(2, 3)

array([[0.85281911, 0.03408987, 0.8935059 ],
       [0.20687912, 0.63852592, 0.47025865]])

In [15]:
# random.randn(m, n) : 표준 정규분포를 따르는 난수로 초기화
# 표준 정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

array([[[-0.00865059,  0.90437382,  0.25068207, -1.01534941,
          0.87763752],
        [ 0.23757588, -1.38330418, -1.79054859,  0.42234007,
         -0.15412066],
        [-1.82788352,  0.35398604,  0.94109767,  0.07553539,
          1.37693039],
        [ 1.36490418, -1.4277767 ,  0.68520906, -0.56661316,
          0.87586682]],

       [[ 0.75261104, -0.35010249, -2.24097368,  0.96112155,
         -1.89645204],
        [ 0.67852428,  0.87899939, -0.97625563, -1.27332588,
         -1.93051063],
        [ 0.23775296, -1.63144221,  0.15141969,  0.74569606,
         -0.86604288],
        [-0.59945559,  0.96681012,  1.06458548,  0.72254728,
          0.41392104]]])

In [16]:
# random.randint(low, high, (size)) : low이상 high미만의 숫자로 size 형태의 정수 배열을 생성
np.random.randint(10, 20, (2, 4))

array([[18, 10, 11, 13],
       [11, 19, 13, 17]], dtype=int32)

In [17]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(30)
np.random.randn(2, 3)

array([[-1.26405266,  1.52790535, -0.97071094],
       [ 0.47055962, -0.10069672,  0.30379318]])

In [18]:
# RNG(Random Number Generator) : 최근 NumPy 사용에서 권장되는 방식
from numpy.random import default_rng

rng = default_rng(seed=42)
rng2 = default_rng(seed=10)

print(rng.random((3, 2)))
print(rng2.random((3, 2)))
print(rng.integers(2, 10, size=3))
print(rng2.integers(2, 10, size=3))
print(rng.normal(0, 1, size=(2, 2)))
print(rng2.normal(0, 1, size=(2, 2)))
print(rng.uniform(5, 10, size=3))
print(rng2.uniform(5, 10, size=3))

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[0.95600171 0.20768181]
 [0.82844489 0.14928212]
 [0.51280462 0.1359196 ]]
[7 8 7]
[5 7 5]
[[-0.01680116 -0.85304393]
 [ 0.87939797  0.77779194]]
[[ 0.47518364 -0.4507686 ]
 [-0.75493228 -0.81481411]]
[8.2193256  9.11380807 7.21707099]
[7.87880274 8.76650932 9.13551969]


## 실습1. 배열 초기화 및 생성

In [19]:
# 1. 0으로 채워진 크기 (3, 4)배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요
np.zeros([3, 4])
np.full((3,4), 5)

# 해설
a1 = np.zeros((3, 4))
a1_2 = np.full((3, 4), 5)
print("문제 1 :", a1, a1_2, sep="\n")

문제 1 :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# 2. 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요
np.arange(0, 21, 2)

# 해설
a2 = np.arange(0, 21, 2)
print("\n문제 2 :", a2)


문제 2 : [ 0  2  4  6  8 10 12 14 16 18 20]


In [21]:
# 3. 0 ~ 1 사이의 실수 난수를 가지는 (2, 3)크기의 배열을 생성하세요
np.random.rand(2, 3)

# 해설
a3 = np.random.rand(2, 3)

print("\n문제 3 : ", a3)


문제 3 :  [[0.51817635 0.76685511 0.93385014]
 [0.08970338 0.19577126 0.99419368]]


In [22]:
# 4. 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요     
print(rng.normal(100, 20,size=(6)))

# 해설 
a4 = np.random.normal(100, 20, 6)
print("\n문제 4 :", a4)

[ 82.81415074 107.37501568  80.82234798 117.56900603  99.00148178
  96.30275273]

문제 4 : [ 84.71904347  84.49622981 127.67694331 115.2077017   94.28708972
 110.76734953]


In [23]:
# 5. 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a = np.arange(1, 21)
a.shape = (4, 5)
print(a)

# 해설
a5 = np.arange(1, 21).reshape(4, 5)
print("\n문제 5 :", a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

문제 5 : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
# 6. 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변화하세요

a = np.linspace(0, 1, 12)
a.shape = (3, 4)

print(a)

# 해설
a6 = np.linspace(0, 1, 12).reshape(3, 4)
print("\n문제 6 :", a6)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]

문제 6 : [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [25]:
# 7. 0 ~ 99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤
# np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
np.random.seed(10)

a = np.random.randint(0, 99, (10, 10))
b = np.eye(10)

print(a)
print(a + b)

# 해설
a7 = np.random.randint(0, 100, (10, 10))
a7_eye = np.eye(10)
a7_add = a7 + a7_eye
print("\n문제 7 :", a7_add)

[[ 9 15 64 28 89 93 29  8 73  0]
 [40 36 16 11 54 88 62 33 72 78]
 [49 51 54 77 69 13 25 13 92 86]
 [30 30 89 12 65 31 57 36 27 18]
 [93 77 22 23 94 11 28 74 88  9]
 [15 18 80 71 88 11 17 46  7 75]
 [28 33 84 96 88 44  5  4 71 88]
 [88 50 54 34 15 77 88 15  6 85]
 [22 11 12 92 96 62 57 79 42 57]
 [97 50 45 40 89 73 37  0 18 23]]
[[10. 15. 64. 28. 89. 93. 29.  8. 73.  0.]
 [40. 37. 16. 11. 54. 88. 62. 33. 72. 78.]
 [49. 51. 55. 77. 69. 13. 25. 13. 92. 86.]
 [30. 30. 89. 13. 65. 31. 57. 36. 27. 18.]
 [93. 77. 22. 23. 95. 11. 28. 74. 88.  9.]
 [15. 18. 80. 71. 88. 12. 17. 46.  7. 75.]
 [28. 33. 84. 96. 88. 44.  6.  4. 71. 88.]
 [88. 50. 54. 34. 15. 77. 88. 16.  6. 85.]
 [22. 11. 12. 92. 96. 62. 57. 79. 43. 57.]
 [97. 50. 45. 40. 89. 73. 37.  0. 18. 24.]]

문제 7 : [[ 4. 29. 16. 84. 82. 14. 51. 79. 17. 50.]
 [53. 26. 48. 17. 32. 81. 80. 41. 90. 12.]
 [30. 81. 18. 16.  0. 31. 73. 64. 38. 22.]
 [96. 66. 67. 63. 95. 99. 27. 82. 62. 77.]
 [48. 93. 75. 86. 38. 11. 21. 33. 95. 43.]
 [88. 96. 73. 4

In [26]:
# 8. 0 ~ 9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
np.random.randint(0, 9, (2, 3, 4))

# 해설
a8 = np.random.randint(0, 9, (2, 3, 4))

print("\n문제 8 :", a8)



문제 8 : [[[6 0 4 6]
  [4 8 0 7]
  [1 7 1 1]]

 [[5 5 0 8]
  [3 7 1 5]
  [2 3 4 5]]]


### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- python의 시퀀스보다 빠름

In [27]:
# 인덱싱
a = np.array([10, 20, 30, 40, 50])
print(a[2])
print(a[-1])

30
50


In [28]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1, 2, 4], [4, 5, 6]]
print("파이썬 인덱싱", matrix[1][1])

# numpy배열
a2 = np.array([[1, 2, 4], [4, 5, 6]])
print("numpy 인덱싱 :", a2[1, 1])

# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2, 3, 4)
print(a3)
print("3차원 인덱싱 :", a3[1, 1, 1])

파이썬 인덱싱 5
numpy 인덱싱 : 5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3차원 인덱싱 : 17


In [29]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# 다차원 슬라이스 : arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원 슬라이스, 1차원 슬라이스]

a1 = np.array([10, 20 ,30, 40, 50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [30]:
# 파이썬 리스트와의 차이
# Python 슬라이스
py_list = [10, 20, 30, 40, 50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본 :", py_list)
print("py슬라이싱", sliced)
print()
# NumPy 슬라이스
np_list = np.array([10, 20, 30, 40, 50])
np_sliced = np_list[1:4]
np_sliced[1] = 100
print("numpy원본 :", np_list)
print("numpy슬라이싱 :", np_sliced)

py원본 : [10, 20, 30, 40, 50]
py슬라이싱 [20, 100, 40]

numpy원본 : [ 10  20 100  40  50]
numpy슬라이싱 : [ 20 100  40]


## 실습 2. 인뎅싱과 슬라이싱

In [34]:
# 1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요.
arr = np.arange(10, 30, 2)
arr1 = arr[1:6:2]
print("문제 1 :", arr1)
print()

# 2. 3 x 3 배열에서 왼쪽 위 -> 오른쪽 아래 대각선 요소만 인덱싱으로 추출하세요
arr = np.arange(1, 10).reshape(3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("문제 2 :", arr[0, 0], arr[1, 1], arr[2, 2])
print()

# 3. 3 x 4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr = np.arange(1, 13).reshape(3, 4)
arr[:,-1] = -1
print("문제 3 :\n", arr)
print()

# 4. 4 x 4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요
arr = np.arange(1, 17).reshape(4, 4)
print("문제 4-1 :\n", arr[::-1],"\n")
print("문제 4-2 :\n", arr[::, ::-1])

문제 1 : [12 16 20]

문제 2 : 1 5 9

문제 3 :
 [[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]

문제 4-1 :
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 

문제 4-2 :
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
