## 02. NumPy

### 2-1 NumPy 배열 연산



In [2]:
import numpy as np

In [3]:
# 배열 간 연산(1차원)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)      # [5 7 9]
print(a1 - a2)      # [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [4]:
# 배열 간 연산(2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + a2)
print(a2 - a1)


[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [5]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1, 2, 3, 4])
print(a1 + 10)      # [11 12 13 14]
print(a1 * 2)       # [2 4 6 8]

[11 12 13 14]
[2 4 6 8]


In [6]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [7]:
# 배열의 구조가 다를 경우
a1 = np.array([1, 2])
a2 = np.array([1, 2, 3])
# print(a1 + a2) # 크기가 다르기 때문에 에러 발생

In [8]:
# 브로드 캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3],
               [4, 5, 6]])  # (2, 3)
a2 = np.array([10, 20, 30]) # 길이가 3인 1차원 배열 (3,)

# 1차원 길이 3
[10, 20 ,30]

# 2차원으로 변현 (1, 3)
[[10, 20, 30]]

# 2차원의 행이 2 -> 2로 확장
[[10, 20, 30],
 [10, 20, 30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [9]:
# 브로드 캐스팅 예제
a1 = np.array([[1], [2], [3]]) # (3, 1)
a2 = np.array([10, 20, 30])    # (3, )

# 과정
# a2 : (3, ) -> (1, 3) 변형
[[10, 20, 30]]

# a1과 a2 비교 -> (3, 1), (1, 3)
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 실습1. 배열연산(1)
# 1. 다음 배열을 생성하고, 모든 요소에 3을 더하세요.
arr = np.array([1, 2, 3, 4])
print("문제 1: ", arr + 3,'\n')

# 2. 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr = np.array([[5, 10],
                [15, 20]])
arr_1 = arr * -1
print("문제 2 : ", arr_1, '\n')
# print("문제 2 : \n", (lambda arr : arr * -1)(np.array([[5, 10], [15, 20]])), '\n')

# 3. 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
print(" 문제 3-1 : ", arr1 * arr2, '\n',"문제 3-2 : ", arr1 / arr2)

문제 1:  [4 5 6 7] 

문제 2 :  [[ -5 -10]
 [-15 -20]] 

 문제 3-1 :  [ 2  8 18] 
 문제 3-2 :  [2. 2. 2.]


In [ ]:
# 4. 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과배열을 브로드 캐스팅으로만드세요.
arr = np.array([[95, 97],
                [80, 85]])
arr_1 = 100 - arr
print("문제 4 :\n ", arr_1,'\n')
# print("문제 4 : \n", (lambda arr : 100 - arr)(np.array([[95, 97], [80, 85]])), '\n')

# 5. 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요.(브로드 캐스팅 이용)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# • 첫 번째행은 10을 곱하고
# • 두 번째행은 100을 곱해야합니다
arr_1 = np.array([[10], [100]])
arr_2 = arr * arr_1
print("문제 5 : \n", arr_2)

문제 4 :
  [[ 5  3]
 [20 15]] 

문제 5 : 
 [[ 10  20  30]
 [400 500 600]]


In [12]:
# 6. 아래배열에서각 행마다 다른 스칼라값을 더하기 위해
# • 1차원 배열을 만들어 브로드 캐스팅 연산을 수행하세요.
# • 첫 번째 행에100, 두 번째 행에200, 세 번째 행에300을 더하세요.
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])
arr_1 = ([100], [200], [300])
print("문제 6 :\n", arr + arr_1)

문제 6 :
 [[110 120]
 [230 240]
 [350 360]]
